### ISSUE TITLE
Separate jediPrep task out of CyclingDA task instead of performing as env-script

### ISSUE THREAD

**Issue by jjguerrette** [NCAR/MPAS-Workflow#20]
jediPrepCyclingDA takes a very long time as the number of EDA members increases.
- [x] jediPrepCyclingDA should be a separate cylc task in the share queue instead of using the same number of processors as CyclingDA.  That will significantly reduce computational overhead for EDA cycling. Closed by #29.
- [x] Create variationalPrep.csh, which moves the inner/outer loop and Ensemble B sed substitution components from jediPrep.csh into a dedicated script for variational applications. Addressed by #31.
- [x] Move the background, static, and template file preparation from variational.csh into variationalPrep.csh in order to run it on a share queue and avoid extra time being spent within the large footprint CyclingDA task. Addressed by #32.
- [x] Ensemble B preparation can be sped up for EDA by more smartly generating the individual Ensemble B member yaml entries in the individual EDA member_N.yaml files (currently resides at the end of `jediPrep.csh`).  Too many repeated `cat` operations and maybe too much `sed` is used now.  Those can be replaced by a much easier-to-follow python script.
